#! /bin/bash

if is_linux; then
    alias upgrade="sudo apt-get update && sudo apt-get upgrade -y"
    alias pbcopy="xsel --clipboard --input"
    alias pbpaste="xsel --clipboard --output"
    alias open="xdg-open"
fi

if is_ubuntu; then
    alias trash=trash-put
    alias bat=batcat
fi

if is_mac; then
    alias upgrade="brew update && brew upgrade"
fi
alias ec="emacsclient -c -n"

alias en="emacs -nw"
alias et="emacsclient -t"

alias xen="TERM=xterm-256color emacs -nw"
alias xet="TERM=xterm-256color emacsclient -t"

alias ten= "TERM=xterm-24bits emacs -nw"
alias tet="TERM=xterm-24bits emacsclient -t"

alias emacs-kill="seartipy_kill_emacs"

alias yi="yarn install"
alias yid="yarn install -D"
alias yrmn="trash node_modules && trash yarn.lock"
alias ys="yarn start"

alias yb="yarn build"
alias yc="yarn clean"
alias ycd="yarn clean:dist"
alias yca="yarn clean:all"
alias yd!="yarn destroy"
alias yt="yarn test"
alias ytw="yarn test:watch"
alias yl="yarn lint"
alias ylf="yarn lint:fix"
alias yu="yarn up"
alias yud="yarn upd"
alias yud="yarn refresh"
alias yv="yarn validate"
alias yty="yarn types"
alias ytyw="yarn types:watch"
alias ycbv="yarn clean && yarn build && yarn validate"

alias m="mkdir -p"

alias a='fasd -a'        # any
alias s='fasd -si'       # show / search / select
alias d='fasd -d'        # directory
alias f='fasd -f'        # file
alias sd='fasd -sid'     # interactive directory selection
alias sf='fasd -sif'     # interactive file selection
alias z='fasd_cd -d'     # cd, same functionality as j in autojump
alias zz='fasd_cd -d -i' # cd with interactive selection

alias c="fasd -d -e code"
alias c.="code ."

alias git-unstage="git reset HEAD"
alias git-discard="git checkout --"
alias gst="git status"
alias gsu="git status -u"
alias tsgfm="git stash && ((git pull --rebase || git pull); git stash pop)"

alias gun="git-unstage"
alias gur="git-discard"
alias gcm="git commit -m"
alias gcne="git commit --no-edit"
alias gca="git commit --amend"
alias gcan="git commit --amend --no-edit"

alias jf="code ~/programs/web/devfractal" # use j maybe?
alias jd="code ~/seartpy/dotfiles" # use j maybe?

if is_ubuntu; then
    alias si="sudo apt-get install -y"
    alias ss="apt-cache search"
    alias sr="sudo apt-get purge"
fi

if is_mac; then
    alias si="brew install"
    alias ss="brew search"
    alias sr="brew uninstall"
fi
