#! /bin/zsh

[ -s ~/.zshrc-pre-local.sh ] && source ~/.zshrc-pre-local.sh

[ -s ~/seartipy/dotfiles/shellrc ] && source ~/seartipy/dotfiles/shellrc

[ -s ~/.zshrc-post-local.sh ] && source ~/.zshrc-post-local.sh

[[ $- == *i* ]] || return 0

[ -s ~/seartipy/vendors/antigen/antigen.zsh ] || git clone https://github.com/zsh-users/antigen.git
source ~/seartipy/vendors/antigen/antigen.zsh

antigen use oh-my-zsh

antigen bundle git
antigen bundle gitfast
antigen bundle git-extras
antigen bundle github

antigen bundle jsontools

antigen bundle command-not-found
antigen bundle common-aliases
antigen bundle dircycle

antigen bundle lein
antigen bundle sbt
antigen bundle scala
antigen bundle cabal
antigen bundle python
antigen bundle web-search

antigen bundle fasd

antigen bundle zsh-users/zsh-history-substring-search

antigen bundle mafredri/zsh-async
antigen bundle sindresorhus/pure
antigen bundle zsh-users/zsh-syntax-highlighting

antigen apply
