#! /bin/zsh

[ -d ~/.oh-my-zsh ] || git clone https://github.com/robbyrussell/oh-my-zsh.git ~/.oh-my-zsh

[[ -s "${HOME}/seartipy/dotfiles/shellrc" ]] && source "${HOME}/seartipy/dotfiles/shellrc"


[[ $- == *i* ]] || return 0

# Path to your oh-my-zsh installation.
export ZSH="${HOME}/.oh-my-zsh"

ZSH_THEME="spaceship"

CASE_SENSITIVE="true"
DISABLE_AUTO_UPDATE="true"

# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

DISABLE_UNTRACKED_FILES_DIRTY="true"

plugins=(
    dirhistory
    history-substring-search
    git 
    fasd 
    git
    git-extras 
    tmux
    fzf
    command-not-found
    alias-finder
    osx
    compleat         
    brew
    common-aliases
    node
    npm
    rand-quote
    sudo
    yarn
    z
    colored-man-pages
    colorize
    cp
    zsh-syntax-highlighting
    zsh-autosuggestions
)

source $ZSH/oh-my-zsh.sh
