#! /bin/zsh

[ -s ~/.zshrc-pre-local.sh ] && source ~/.zshrc-pre-local.sh

[ -s ~/seartipy/dotfiles/shellrc ] && source ~/seartipy/dotfiles/shellrc

[ -s ~/.zshrc-post-local.sh ] && source ~/.zshrc-post-local.sh

[[ $- == *i* ]] || return 0

[ -d ~/.zgen ] || git clone https://github.com/tarjoilija/zgen.git ~/.zgen

[ -s ~/.zgen/zgen.zsh ] || return 1

ZGEN_PREZTO_LOAD_DEFAULT=false
ZGEN_RESET_ON_CHANGE=(${HOME}/.zshrc ${HOME}/.zgen-options-local.sh ${HOME}/.zgen-plugins-local.sh)
source ~/.zgen/zgen.zsh

# check if there's no init script
if ! zgen saved; then
    echo "Creating a zgen save"

    # prezto options
    zgen prezto editor key-bindings 'emacs'
    zgen prezto editor dot-expansion 'yes'

    zgen prezto prompt theme 'pure'
    zgen prezto terminal auto-title 'yes'
    zgen prezto utility:ls color 'yes'
    zgen prezto syntax-highlighting color 'yes'
    zgen prezto syntax-highlighting highlighters 'main' 'brackets'

    [ -s ~/.zgen-options-local.sh ] || touch ~/.zgen-options-local.sh
    source ~/.zgen-options-local.sh

    # prezto and modules
    zgen prezto
    zgen prezto environment
    zgen prezto utility
    zgen prezto terminal
    zgen prezto editor
    zgen prezto history
    zgen prezto directory
    zgen prezto spectrum
    zgen prezto completion                     # must be loaded after utility
    zgen prezto archive                        # lsarchive and unarchive commands
    zgen prezto git                            # git aliases
    zgen prezto command-not-found
    zgen prezto fasd                           # j , f, d etc.
    zgen prezto osx
    [[ "$ZGEN_SYNTAX_HIGHLIGHTING" == "yes" ]] && zgen prezto syntax-highlighting
    zgen prezto history-substring-search
    [[ "$ZGEN_AUTO_SUGGESIONS" == "yes" ]] && zgen prezto autosuggestions

    # plugins
    zgen load djui/alias-tips
    zgen load rimraf/k

    zgen load andrewferrier/fzf-z
    zgen load unixorn/tumult.plugin.zsh
    zgen load peterhurford/git-it-on.zsh
    zgen load unixorn/git-extra-commands
    zgen load paulirish/git-open

    [ -s ~/.zgen-plugins-local.sh ] || touch ~/.zgen-plugins-local.sh
    source ~/.zgen-plugins-local.sh

    zgen prezto prompt          # prompt must be the last module to load
    zgen save                   # save all to init script
fi

# copied from tmux prezto module
# start_tmux() {
#     tmux start-server

#     # Create a 'seartipy' session if no session has been defined in tmux.conf.
#     if ! tmux has-session 2> /dev/null; then
#         tmux_session='seartipy'
#         tmux \
#             new-session -d -s "$tmux_session" \; \
#             set-option -t "$tmux_session" destroy-unattached off &> /dev/null
#     fi

#     # Attach to the 'prezto' session or to the last session used.
#     exec tmux attach-session
# }

# [ -n "$SEARTIPY_TMUX" ] && [[ -z "$SEARTIPY_EMACS" && -z "$TMUX" && -z "$EMACS" && -z "$INSIDE_EMACS" && -z "$VIM" ]] && start_tmux
