source $INSTALLER_SCRIPTS/$OS/essential.sh
source $INSTALLER_SCRIPTS/$OS/java.sh
source $INSTALLER_SCRIPTS/$OS/clojure.sh
source $INSTALLER_SCRIPTS/$OS/scala.sh
source $INSTALLER_SCRIPTS/$OS/python.sh
source $INSTALLER_SCRIPTS/$OS/web.sh
source $INSTALLER_SCRIPTS/$OS/cpp.sh
source $INSTALLER_SCRIPTS/$OS/haskell.sh
source $INSTALLER_SCRIPTS/$OS/ruby.sh
source $INSTALLER_SCRIPTS/$OS/additional.sh
source $INSTALLER_SCRIPTS/$OS/vim.sh
