sudo apt-get install -y clang
sudo apt-get install -y libclang-dev
sudo apt-get install -y libc++-dev
sudo apt-get install -y libc++abi-dev
sudo apt-get install -y libboost-all-dev
sudo apt-get install -y g++
sudo apt-get install -y cppcheck
sudo apt-get install -y scons
sudo apt-get install -y cmake
