source $INSTALLER_SCRIPTS/linux/lib/essential.sh
source $INSTALLER_SCRIPTS/linux/lib/java.sh
source $INSTALLER_SCRIPTS/linux/lib/clojure.sh
source $INSTALLER_SCRIPTS/linux/lib/scala.sh
source $INSTALLER_SCRIPTS/linux/lib/python.sh
source $INSTALLER_SCRIPTS/linux/lib/web.sh
source $INSTALLER_SCRIPTS/linux/lib/cpp.sh
source $INSTALLER_SCRIPTS/linux/lib/haskell.sh
source $INSTALLER_SCRIPTS/linux/lib/ruby.sh
source $INSTALLER_SCRIPTS/linux/lib/additional.sh
source $INSTALLER_SCRIPTS/linux/lib/vim.sh
