#! /usr/bin/env bash

{

DOTFILES_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && cd .. && pwd )"

source "$DOTFILES_DIR/scripts/utils.sh"

haskell_install() {
    slog "Installing stack"
    curl -sSL https://get.haskellstack.org/ | sh

    slog "Installing stack packages"
    stack setup
    stackexei alex
    stackexei happy
    stackexei hlint
    # stackexei structured-haskell-mode
    stackexei stylish-haskell
    stackexei hasktags
    stackexei hindent
    stackexei hdevtools
    # stackexei ghc-mod
    # stackexei ghci-ng
    stackexei apply-refact
    stackexei hoogle
    stackexei intero
    # ihaskell_install
}

fresh_haskell() {
    if [ -n "$HASKELL" ]; then
        srm ~/.ghc
        srm ~/.stack
        srm ~/.cabal
    fi
}

haskell_check() {
    cmd_check alex happy hlint stylish-haskell hasktags hindent hdevtools hoogle intero
}

installer() {
    create_dirs
    haskell_install
    haskell_check
}

curdir=$(pwd)

if is_ubuntu; then
    trash-put ~/seartipy-installer.log ~/seartipy-error.log ~/seartipy-output.log 2> /dev/null
else
    trash ~/seartipy-installer.log ~/seartipy-error.log ~/seartipy-output.log 2> /dev/null
fi

keep_sudo_running

export PATH="$HOME/bin:$PATH"

pre_installer_check

installer "$@" > >(tee ~/seartipy-output.log) 2> >(tee ~/seartipy-error.log >&2)

cd "$curdir"

}