SEARTIPY_HOME=$HOME

function spull {
    if [ -e $1 ]; then
        cd $1
        if git status --porcelain > /dev/null; then
            git pull origin master
        fi
        popd > /dev/null
    fi
}

function upgrade_system {
    if [[ "$OSTYPE" == "linux-gnu" ]]; then
        sudo apt-get update && sudo apt-get upgrade -y
    elif [[ "$OSTYPE" == "darwin"* ]]; then
        brew update && brew upgrade && brew cleanup && brew cask cleanup
    fi
}

function upgrade_dotfiles {
    spull SEARTIPY_HOME/dotfiles
}

function upgrade_emacs {
    if [[ "$OSTYPE" == "linux-gnu" ]]; then
        cask upgrade
    fi
    spull $SEARTIPY_HOME/housem.d
    pushd . > /dev/null
    cd $SEARTIPY_HOME/housem.d > /dev/null && cask update
    popd > /dev/null

    spull SEARTIPY_HOME/spacemacs
    spull SEARTIPY_HOME/purcell
    spull SEARTIPY_HOME/prelude
    spull SEARTIPY_HOME/magnars
}

function upgrade_clojure {
    if [[ "$OSTYPE" == "linux-gnu" ]]; then
        lein upgrade
    fi
    lein ancient upgrade-profiles :allow-snapshots
}

function upgrade_scala {
    expect > /dev/null <<EOF
spawn sbt console
expect "scala>"
send ":quit\r"
EOF
}

function upgrade_web {
    nvm install 0.12
    npm upgrade -g
}

function upgrade_all {
    upgrade
    upgrade_dotfiles
    upgrade_emacs
    upgrade_clojure
    upgrade_scala
    upgrade_web
}

source $SEARTIPY_HOME/antigen/antigen.zsh

antigen use oh-my-zsh

antigen bundle git
antigen bundle gitfast
antigen bundle git-extras
antigen bundle github
antigen bundle jsontools

antigen bundle command-not-found
antigen bundle autojump
antigen bundle common-aliases
antigen bundle dircycle
antigen bundle dirhistory

antigen bundle lein
antigen bundle sbt
antigen bundle scala
antigen bundle cabal
antigen bundle python
antigen bundle ruby
antigen bundle pip
antigen bundle coffee

antigen bundle atom
antigen bundle sublime
antigen bundle web-search

antigen bundle fasd

antigen bundle zsh-users/zsh-history-substring-search

if [ -n "$INSIDE_EMACS" ]; then
    antigen theme robbyrussell
else
    antigen bundle nojhan/liquidprompt
    antigen bundle zsh-users/zsh-syntax-highlighting
fi

antigen apply

#node
export NVM_DIR="$HOME/.nvm"
[ -s "$HOME/.nvm/nvm.sh" ] && source "$HOME/.nvm/nvm.sh"

#java
if [[ "$OSTYPE" == "linux-gnu" ]]; then
    export JAVA_HOME="/usr/lib/jvm/java-8-oracle"
    export JDK_HOME="/usr/lib/jvm/java-8-oracle"

    alias upgrade="sudo apt-get update && sudo apt-get upgrade -y"

    export PATH="/opt/ghc/7.10.2/bin:$PATH"
    alias cabal="cabal-1.22"

    alias pbcopy="xsel --clipboard --input"
    alias pbpaste="xsel --clipboard --output"
    alias open="xdg-open"

    alias e="TERM=xterm-256color emacs -nw"

elif [[ "$OSTYPE" == "darwin"* ]]; then
    export JAVA_HOME=`/usr/libexec/java_home -v 1.8`
    export JDK_HOME=`/usr/libexec/java_home -v 1.8`

    alias upgrade="brew update && brew upgrade"
fi

alias tmux="tmux -u -2" #force tmux to use unicode and 256 colors
export PATH="$PATH:$SEARTIPY_HOME/bin"

#ruby
export PATH="$HOME/.rvm/bin:$PATH" # Add RVM to PATH for scripting

#haskell
export PATH="$HOME/.cabal/bin:$PATH"

export PATH="$HOME/.cask/bin:$PATH"

