source ~/antigen/antigen.zsh

antigen use oh-my-zsh

antigen bundle nojhan/liquidprompt

antigen bundle git
antigen bundle gitfast
antigen bundle git-extras
antigen bundle github
antigen bundle jsontools

antigen bundle command-not-found
antigen bundle autojump
antigen bundle common-aliases
antigen bundle dircycle
antigen bundle dirhistory

antigen bundle lein
antigen bundle sbt
antigen bundle scala
antigen bundle cabal
antigen bundle python
antigen bundle ruby
antigen bundle pip
antigen bundle coffee

antigen bundle atom
antigen bundle sublime
antigen bundle web-search

antigen bundle zsh-users/zsh-syntax-highlighting

antigen apply

#node
export NVM_DIR="$HOME/.nvm"
[ -s "$HOME/.nvm/nvm.sh" ] && source "$HOME/.nvm/nvm.sh"

#java
if [[ "$OSTYPE" == "linux-gnu" ]]; then
    export JAVA_HOME="/usr/lib/jvm/java-8-oracle"
    export JDK_HOME="/usr/lib/jvm/java-8-oracle"
    #python
    export PATH="$HOME/anaconda3/bin:$PATH"
elif [[ "$OSTYPE" == "darwin"* ]]; then
    export JAVA_HOME=`/usr/libexec/java_home -v 1.8`
    export JDK_HOME=`/usr/libexec/java_home -v 1.8`
    #python
    export PATH="$HOME/anaconda/bin:$PATH"
fi

alias tmux="tmux -u"
export PATH="$PATH:$HOME/bin"

#ruby
export PATH="$HOME/.rvm/bin:$PATH" # Add RVM to PATH for scripting
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM
