source ~/antigen/antigen.zsh

antigen use oh-my-zsh

antigen bundle git
antigen bundle gitfast
antigen bundle git-extras
antigen bundle github
antigen bundle jsontools

antigen bundle command-not-found
antigen bundle autojump
antigen bundle common-aliases
antigen bundle dircycle
antigen bundle dirhistory

antigen bundle lein
antigen bundle sbt
antigen bundle scala
antigen bundle cabal
antigen bundle python
antigen bundle ruby
antigen bundle pip
antigen bundle coffee

antigen bundle atom
antigen bundle sublime
antigen bundle web-search

antigen bundle zsh-users/zsh-history-substring-search

if [ -n "$INSIDE_EMACS" ]; then
    antigen theme robbyrussell
else
    antigen bundle nojhan/liquidprompt
    antigen bundle zsh-users/zsh-syntax-highlighting
fi

antigen apply

#node
export NVM_DIR="$HOME/.nvm"
[ -s "$HOME/.nvm/nvm.sh" ] && source "$HOME/.nvm/nvm.sh"

#java
if [[ "$OSTYPE" == "linux-gnu" ]]; then
    export JAVA_HOME="/usr/lib/jvm/java-8-oracle"
    export JDK_HOME="/usr/lib/jvm/java-8-oracle"

    alias upgrade="sudo apt-get update && sudo apt-get upgrade -y"

    export PATH="/opt/ghc/7.10.2/bin:$PATH"
    alias cabal="cabal-1.22"

elif [[ "$OSTYPE" == "darwin"* ]]; then
    export JAVA_HOME=`/usr/libexec/java_home -v 1.8`
    export JDK_HOME=`/usr/libexec/java_home -v 1.8`

    alias upgrade="brew update && brew upgrade"
fi

alias tmux="tmux -u"
export PATH="$PATH:$HOME/bin"

#ruby
export PATH="$HOME/.rvm/bin:$PATH" # Add RVM to PATH for scripting
